name: Build

on: [push, pull_request]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet build -c Release src/OpenRGB.NET/OpenRGB.NET.csproj
